#!/bin/sh
set -eu

RUNTIME_CONFIG_PATH="/srv/runtime-config.js"

escape_js() {
  printf "%s" "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

API_BASE_URL="${DEALBOT_API_BASE_URL:-${VITE_API_BASE_URL:-}}"
PLAUSIBLE_DATA_DOMAIN="${VITE_PLAUSIBLE_DATA_DOMAIN:-}"
DASHBOARD_URL="${DASHBOARD_URL:-${VITE_DASHBOARD_URL:-}}"
DASHBOARD_EMBED_URL="${DASHBOARD_EMBED_URL:-${VITE_DASHBOARD_EMBED_URL:-}}"
APPROVED_SP_DASHBOARD_URL_MAINNET="${APPROVED_SP_DASHBOARD_URL_MAINNET:-${VITE_APPROVED_SP_DASHBOARD_URL_MAINNET:-}}"
APPROVED_SP_DASHBOARD_URL_CALIBRATION="${APPROVED_SP_DASHBOARD_URL_CALIBRATION:-${VITE_APPROVED_SP_DASHBOARD_URL_CALIBRATION:-}}"
LOGS_URL="${LOGS_URL:-${VITE_LOGS_URL:-}}"

API_BASE_URL_ESCAPED="$(escape_js "$API_BASE_URL")"
PLAUSIBLE_DATA_DOMAIN_ESCAPED="$(escape_js "$PLAUSIBLE_DATA_DOMAIN")"
DASHBOARD_URL_ESCAPED="$(escape_js "$DASHBOARD_URL")"
DASHBOARD_EMBED_URL_ESCAPED="$(escape_js "$DASHBOARD_EMBED_URL")"
APPROVED_SP_DASHBOARD_URL_MAINNET_ESCAPED="$(escape_js "$APPROVED_SP_DASHBOARD_URL_MAINNET")"
APPROVED_SP_DASHBOARD_URL_CALIBRATION_ESCAPED="$(escape_js "$APPROVED_SP_DASHBOARD_URL_CALIBRATION")"
LOGS_URL_ESCAPED="$(escape_js "$LOGS_URL")"

cat > "$RUNTIME_CONFIG_PATH" <<EOF
window.__DEALBOT_CONFIG__ = {
  API_BASE_URL: "${API_BASE_URL_ESCAPED}",
  PLAUSIBLE_DATA_DOMAIN: "${PLAUSIBLE_DATA_DOMAIN_ESCAPED}",
  DASHBOARD_URL: "${DASHBOARD_URL_ESCAPED}",
  DASHBOARD_EMBED_URL: "${DASHBOARD_EMBED_URL_ESCAPED}",
  APPROVED_SP_DASHBOARD_URL_MAINNET: "${APPROVED_SP_DASHBOARD_URL_MAINNET_ESCAPED}",
  APPROVED_SP_DASHBOARD_URL_CALIBRATION: "${APPROVED_SP_DASHBOARD_URL_CALIBRATION_ESCAPED}",
  LOGS_URL: "${LOGS_URL_ESCAPED}"
};
EOF

exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
