apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dealbot
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - dealbot
  selector:
    matchLabels:
      app.kubernetes.io/name: dealbot
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
