apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dealbot-worker
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - dealbot
  selector:
    matchLabels:
      app.kubernetes.io/name: dealbot-worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
