apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dealbot-postgres
  labels:
    app.kubernetes.io/name: dealbot-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
