name: docker-build
description: Build a Docker image with BuildKit + GHA cache (optionally push or load).

inputs:
  context:
    description: Docker build context
    required: false
    default: .
  file:
    description: Path to Dockerfile
    required: true
  tags:
    description: Newline-separated image tags
    required: true
  platforms:
    description: Target platforms (only relevant when pushing)
    required: false
    default: linux/amd64
  push:
    description: Push image to registry
    required: false
    default: "false"
  load:
    description: Load image into local Docker daemon
    required: false
    default: "false"
  cache-scope:
    description: Scope key for GHA build cache
    required: true
  setup-buildx:
    description: Whether to set up docker buildx
    required: false
    default: "true"
  login:
    description: Whether to login to a registry
    required: false
    default: "false"
  registry:
    description: Registry hostname for login
    required: false
    default: ghcr.io
  username:
    description: Registry username for login
    required: false
    default: ""
  password:
    description: Registry password/token for login
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      if: inputs.setup-buildx == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Login to registry
      if: inputs.login == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        tags: ${{ inputs.tags }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        cache-from: type=gha,scope=${{ inputs.cache-scope }}
        cache-to: type=gha,mode=max,scope=${{ inputs.cache-scope }}
        platforms: ${{ inputs.platforms }}
