apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealbot
spec:
  template:
    spec:
      containers:
        - name: dealbot
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
