apiVersion: v1
kind: Service
metadata:
  name: dealbot-worker
  labels:
    app.kubernetes.io/name: dealbot-worker
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      nodePort: 30082
      protocol: TCP
  selector:
    app.kubernetes.io/name: dealbot-worker
